Update integration test workflow to handle backup file path and size validation; change test database name to odoo_test_16

diff --git a/.github/workflows/integration-test.yml b/.github/workflows/integration-test.yml
--- a/.github/workflows/integration-test.yml
+++ b/.github/workflows/integration-test.yml
@@ -76,22 +76,27 @@ jobs:
         env:
           SERVER_HOST: ${{ secrets.SERVER_HOST }}
           SERVER_USER: ubuntu
-          SERVER_SSH_PORT: 22
-          BACKUP_PATH: /tmp/odoo/backup/bep/main/odoo_2025-06-19_03-45-27.zip
+          SERVER_SSH_PORT: ${{ secrets.SERVER_SSH_PORT }}
+          BACKUP_PATH: ${{ steps.backup-on-server.outputs.script-output }}
         run: |
-          
-          size=$(ssh -o StrictHostKeyChecking=no -p $SERVER_SSH_PORT $SERVER_USER@$SERVER_HOST "stat -c %s '$BACKUP_PATH'" || echo "")
-          if ! [[ "$size" =~ ^[0-9]+$ ]]; then
-            echo "Error: Could not get size or invalid: '$size'"
+          if [[ -z "$SERVER_HOST" || -z "$SERVER_USER" || -z "$BACKUP_PATH" ]]; then
+            echo "Error: SERVER_HOST, SERVER_USER hoặc BACKUP_PATH trống"
             exit 1
           fi
-          # Compare bytes directly:
-          threshold=$((10*1024*1024*1024))
+
+          size=$(ssh -o StrictHostKeyChecking=no -p "$SERVER_SSH_PORT" "$SERVER_USER@$SERVER_HOST" "stat -c %s '$BACKUP_PATH'" 2>/dev/null || echo "")
+          if ! [[ "$size" =~ ^[0-9]+$ ]]; then
+            echo "Error: Không lấy được size hoặc invalid: '$size'"
+            exit 1
+          fi
+
+          threshold=$((10 * 1024 * 1024 * 1024))
           if (( size > threshold )); then
             echo "use_self_hosted=true" >> "$GITHUB_OUTPUT"
           else
             echo "use_self_hosted=false" >> "$GITHUB_OUTPUT"
           fi
+  
   
 
   integration-test:
